name: 'Checkout the whole repository'
description: 'Checkout all commits, all tags, and initialize all submodules.'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Fetch tags
      shell: bash
      run: git fetch --tags -f
