name: 'Checkout the whole repository'
description: 'Checkout all commits, all tags, and initialize all submodules.'
inputs:
  token:
    description: The token to use when checking out the repository
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout with custom token
      uses: actions/checkout@v6.0.1
      if: inputs.token != ''
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ inputs.token }}
    - name: Checkout with default token
      uses: actions/checkout@v6.0.1
      if: inputs.token == ''
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Recreate checkout v5 credentials
      shell: bash
      run: |
        # Set the PAT as a basic auth header (what checkout v5 used to do)
        git config http.https://github.com/.extraheader \
          "AUTHORIZATION: basic $(printf 'x-access-token:%s' '${{ secrets.DEPLOYMENT_TOKEN }}' | base64 | tr -d '\n')"
    - name: Fetch tags
      shell: bash
      run: git fetch --tags -f
