name: Release
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    strategy:
      matrix:
        os: [ windows, macos, ubuntu ]
        token: [ '', '${{ secrets.GITHUB_TOKEN }}' ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: action
      - uses: ./action
        with:
          token: ${{ matrix.token }}
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Semantic Release
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
