name: Release
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    strategy:
      matrix:
        os: [ windows, macos, ubuntu ]
        custom_token: [ true, false ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: action
      - name: Test with custom token
        uses: ./action
        if: matrix.custom_token == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with default token
        uses: ./action
        if: matrix.custom_token == 'false'
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Semantic Release
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
