on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  Try-To-Checkout:
    runs-on: ubuntu-20.04
    steps:
      - uses: danysk/action-checkout@${{ github.sha }}
      - runs: git describe
